### ISSUE TITLE
can't run under windows

### ISSUE THREAD

**Issue by mainpart** [aliforever/gomondel#1]
C:\path>gomondel --init=MediaMovieInvest                                                                                                                                   
fmt path C:\path/models                                                                                                                                                    
exit status 2: CreateFile C:\path/models: The system cannot find the file specified.  

after creating folder models manualy program runs but  db and models folders are empty

fmt path C:\path/models                                                                                                                                                    
fmt path C:\path/                                                                                                                                                          
Database MediaMovieInvest init file added in /models/init.go, don't forget to call InitMongoDB() in your main function

**Comment by aliforever** [comment]
Hi, sorry for the late reply. My GitHub was suspended. Thank you, I approved your pull request.
